<?php
echo '<!DOCTYPE html>                                                                                                                                                                                                         ';
echo '<html>';
echo '    <head>';
echo '        <link rel="stylesheet" href="./assets/bootstrap-3.3.7-dist/css/bootstrap.css">';
echo '        <title>Home</title>';
echo '    </head>';
echo '    <body>';
echo '          <div class="panel-group">';
echo '            <div class="panel panel-default">';
echo '              <div class="panel-body">';
echo '                <h2>ACADEMIC PROJECTS</h2>';
echo '                <strong>Software Engineering Group Project</strong><br/>';
echo '                    <em>Volunteer Full-Stack Developer</em><br/>';
echo '                    <ul class="list-group">';
echo '                    <li class="list-group-item">HTML, CSS, JavaScript, and JQuery used for front-end design and DOM manipulation</li>';
echo '                    <li class="list-group-item">AJAX used to asynchronously query API server, utilizing JQuery for targeting the DOM</li>';
echo '                    <li class="list-group-item">Node.js used to run the API server, utilizing the Express.js framework as middleware</li>';
echo '                    <li class="list-group-item">AWS MySQL RDS Instance used for data persistence</li>';
echo '                    <li class="list-group-item">Insomnia used for API-testing, MySQL Workbench as an interfacing tool for the database</li>';
echo '                    <li class="list-group-item">Customer can create account; logging in uses cookies for login-session persistence</li>';
echo '                    <li class="list-group-item">Customer searches for hotels by city: they can book a reservation, and delete their reservations</li>';
echo '                    <li class="list-group-item">Hotel admins can add properties, add rooms, and create or delete reservations for customers</li>';
echo '                    <li class="list-group-item">Chat-bot with Google\'s Dialogflow; Kommunicate used for taking over conversation with bot</li>';
echo '                    <li class="list-group-item">Authentication implemented, ensuring only credentialed accounts can use certain features</li>';
echo '                    </ul>';
echo '              </div>';
echo '            </div>';
echo '          </div>';
echo '          <nav class="navbar navbar-inverse navbar-fixed-bottom">';
echo '            <div class="container-fluid">';
echo '              <div class="navbar-header">';
echo '                <a class="navbar-brand" href="#">Travis\' Resume Website Footer</a>';
echo '              </div>';
echo '            </div>';
echo '          </nav> ';
echo '    </body>';
echo '</html>';
?>