<?php
echo '<!DOCTYPE html>                                                                                                                                                                                                   ';
echo '<html>';
echo '    <head>';
echo '        <link rel="stylesheet" href="./assets/bootstrap-3.3.7-dist/css/bootstrap.css">';
echo '        <title>School</title>';
echo '    </head>';
echo '    <body>';
echo '            <h2>CAREER OBJECTIVE</h2>';
echo '            <strong>I am seeking a position in a technological company that takes pride in its ability to be<br/>';
echo '            innovative, where I can expand my technical skills and contribute to my passion for software development</strong>';
echo '            <h2>SUMMARY OF QUALIFICATIONS</h2>';
echo '            <ul class="list-group">';
echo '            <li class="list-group-item">Experience in developing REST APIs, reading technical documentation, writing re-usable code</li>';
echo '            <li class="list-group-item">Front-End and Back-End Web Development utilizing Software Development Lifecycle best practices</li>';
echo '            <li class="list-group-item">Experience in utilizing a variety of Web Development Tools for reporting, error checking, and data compliance</li>';
echo '            </ul>';
echo '                    <h2>EDUCATION</h2>';
echo '            The University of Texas at San Antonio - Cumulative GPA: 3.85<br/>';
echo '            <strong>Bachelor of Science, B.S., Computer Science</strong> - Graduation: May/2022<br /><br/>';
echo '            <strong>Relevant Coursework</strong><br/>';
echo '            <ul class="list-group">';
echo '            <li class="list-group-item">Software Engineering</li>';
echo '            <li class="list-group-item">Cloud Computing</li>';
echo '            <li class="list-group-item">Web Technologies</li>';
echo '            <li class="list-group-item">Computer Networks</li>';
echo '            </ul>';
echo '            <strong>RELEVANT SKILLS</strong><br/>';
echo '            <ul class="list-group">';
echo '            <li class="list-group-item">Programming Languages - Java, C, Python, JavaScript, CSS, HTML, SQL</li>';
echo '            <li class="list-group-item">Programming Frameworks / Operating Systems - React.js, Express.js, Node.js, Linux, Windows, iOS, Android</li>';
echo '            <li class="list-group-item">Software - AWS CLI, AWS Console, AWS API, MySQL Workbench, Microsoft Suites</li>';
echo '            </ul>';
echo '            <div class="media">';
echo '                <div class="media-left">';
echo '                  <img src="images/UTSA.jpg" class="media-object" style="width:200px">';
echo '                </div>';
echo '              </div>';
echo '              <nav class="navbar navbar-inverse navbar-fixed-bottom">';
echo '                <div class="container-fluid">';
echo '                  <div class="navbar-header">';
echo '                    <a class="navbar-brand" href="#">Travis\' Resume Website Footer</a>';
echo '                  </div>';
echo '                </div>';
echo '              </nav>';
echo '        </table>';
echo '    </body>';
echo '</html>';
?>