<?php
echo '<!DOCTYPE html>                                                                                                                                                                                                         ';
echo '<html>';
echo '    <head>';
echo '        <link rel="stylesheet" href="./assets/bootstrap-3.3.7-dist/css/bootstrap.css">';
echo '        <title>Work</title>';
echo '    </head>';
echo '    <body>';
echo '        <nav class="navbar navbar-inverse">';
echo '            <div class="container-fluid">';
echo '              <div class="navbar-header">';
echo '                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">';
echo '                  <span class="icon-bar"></span>';
echo '                  <span class="icon-bar"></span>';
echo '                  <span class="icon-bar"></span>';
echo '                </button>';
echo '                <a class="navbar-brand" href="#">Travis Sauer\'s Resume Website</a>';
echo '              </div>';
echo '              <div class="collapse navbar-collapse" id="myNavbar">';
echo '                <ul class="nav navbar-nav">';
echo '                  <li class="active"><a href="./home.php">Home</a></li>';
echo '                  <li><a href="./work.php">Work</a></li>';
echo '                  <li><a href="./school.php">School</a></li>';
echo '                  <li><a href="./contact.php">Contact</a></li>';
echo '                </ul>';
echo '              </div>';
echo '            </div>';
echo '          </nav>';
echo '                    <h2>WORK EXPERIENCE</h2>';
echo '            <strong>Patterson-UTI Drilling Company LLC,</strong> Victoria, TX - 2017-2019<br/>';
echo '            <em>Lead Floor Hand</em>';
echo '            <ul class="list-group">';
echo '            <li class="list-group-item">Trained employees that were new to the industry; discussed safety culture and compliance</li>';
echo '            <li class="list-group-item">Performed mechanical inspections and maintenance to promote a safer and more efficient environment</li>';
echo '            </ul>';
echo '            <strong>Trifecta Oilfield Services,</strong> Stockdale, TX - 2014-2017<br/>';
echo '            <em>Service Crew Leader</em>';
echo '            <ul class="list-group">';
echo '            <li class="list-group-item">Communicated with client about scope and expectations regarding the service contract</li>';
echo '            <li class="list-group-item">Collaborated with coworkers, discussing client expectations and steps needed for task completion</li>';
echo '            </ul>';
echo '                    <h2>RELEVANT TRAINING AND CERTIFICATIONS</h2>';
echo '            <ul class="list-group">';
echo '            <li class="list-group-item"><a href="https://www.credly.com/badges/d92ee07a-4fba-4512-abe5-11fddec4c46c?source=linked_in_profile">';
echo '                Amazon Web Services (AWS) DevOps Professional - CICD/SDLC principles 2021</a></li>';
echo '            <li class="list-group-item"><a href="https://www.credly.com/badges/255e0254-2821-428e-947e-7c533a69b53b/public_url">';
echo '                Amazon Web Services (AWS) Solutions Architect Associate - Cloud Computing Architectural principles 2021</a></li>';
echo '            <li class="list-group-item"><a href="https://www.credly.com/badges/4a588d0e-b701-4fdd-ae58-93026a86c135?source=linked_in_profile">';
echo '                CompTIA Security + - Security/Business compliance principles 2021';
echo '            </a></li>';
echo '            </ul>';
echo '                <h2>Computer Science Proficiencies</h2>           ';
echo '                <table class="table table-bordered">';
echo '                  <thead>';
echo '                    <tr>';
echo '                      <th>Languages</th>';
echo '                      <th>Operating Systems</th>';
echo '                      <th>Tools</th>';
echo '                      <th>Skill Level</th>';
echo '                    </tr>';
echo '                  </thead>';
echo '                  <tbody>';
echo '                    <tr>';
echo '                      <td>Java</td>';
echo '                      <td>Windows</td>';
echo '                      <td>Amazon Web Services Console</td>';
echo '                      <td>Expert</td>';
echo '                    </tr>';
echo '                    <tr>';
echo '                      <td>C</td>';
echo '                      <td>Linux</td>';
echo '                      <td>Insomnia (Postman-like tool)</td>';
echo '                      <td>Advanced</td>';
echo '                    </tr>';
echo '                    <tr>';
echo '                      <td>JavaScript</td>';
echo '                      <td>Android</td>';
echo '                      <td>PHPMyAdmin</td>';
echo '                      <td>Advanced</td>';
echo '                    </tr>';
echo '                    <tr>';
echo '                        <td>Python</td>';
echo '                        <td>iOS</td>';
echo '                        <td>MySQL Workbench</td>';
echo '                        <td>Advanced</td>';
echo '                      </tr>';
echo '                  </tbody>';
echo '                </table>';
echo '                <div class="media">';
echo '                    <div class="media-left">';
echo '                      <img src="images/AWS.png" class="media-object" style="width:200px">';
echo '                    </div>';
echo '                  </div>';
echo '                  <nav class="navbar navbar-inverse navbar-fixed-bottom">';
echo '                    <div class="container-fluid">';
echo '                      <div class="navbar-header">';
echo '                        <a class="navbar-brand" href="#">Travis\' Resume Website Footer</a>';
echo '                      </div>';
echo '                    </div>';
echo '                  </nav>';
echo '    </body>';
echo '</html>';
?>